export { default as Header } from "./header"
export { default as Hero } from "./hero"
export { default as Features } from "./features"
export { default as HowItWorks } from "./how-it-works"
export { default as Benefits } from "./benefits"
export { default as FAQ } from "./faq"
export { default as Footer } from "./footer"
